### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by gerryfrank10**
Added A readme file

### CODE REVIEW

**Comment by jugginedwards** [comment]
All checks failed fam. Kindly look it up again and make necessary corrections. Thanks.

**Comment by jugginedwards** [comment]
It had one errored check!

**Comment by jugginedwards** [comment]
Kindly review the code and ensure that you apply the needed corrections. I just enabled dev1 for review on Codacy; Hopefully it should have been reviewed by Codacy by the time you're checking this.

How to do this is pretty easy:

Click on the details link of Codacy/PR Quality Review to find the details about the errors found, there might just be a missing semicolon or some other kind of errors, but trust me it would show you exactly where all the errors are in the code 

Cheers man!

**Comment by gerryfrank10** [comment]
Added a readme

**Review by jugginedwards — APPROVED** [review]

**Pull request merged**
